animal = input ("What's your favoite animal? \n")
like = input ("Why do you like them? \n")
color = input ("What color are they? \n")
fact = input ("What is a fun fact about them? \n")
live = input ("Where do they live? \n")
eat = input ("What do they like to eat? \n")
print ("Your favorite animal is a " + animal + " because " + like + "." + " They live in " + live + " and " + fact + ". They are " + color)